/**
 *
 *  AutomatedServices.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/BaseBuilder.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/SqlBinder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <iostream>
#include <json/json.h>
#include <memory>
#include <stdint.h>
#include <string>
#include <string_view>
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <tuple>
#include <vector>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
} // namespace orm
} // namespace drogon
namespace drogon_model
{
namespace sgrn
{
namespace core
{

class AutomatedServices {
public:
    struct Cols {
        static const std::string _id;
        static const std::string _organisation;
        static const std::string _name;
        static const std::string _description;
        static const std::string _token;
        static const std::string _token_secret_hash;
        static const std::string _domain;
        static const std::string _deleted_at;
        static const std::string _status;
        static const std::string _metadata;
        static const std::string _total_virtual_size;
        static const std::string _total_real_size;
        static const std::string _storage_limit;
        static const std::string _total_entry_count;
        static const std::string _entry_count_limit;
        static const std::string _created_at;
        static const std::string _updated_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType& getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit AutomatedServices(const drogon::orm::Row& r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit AutomatedServices(const Json::Value& pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    AutomatedServices(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false);

    AutomatedServices() = default;

    void updateByJson(const Json::Value& pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value& pJson, std::string& err);
    static bool validateMasqueradedJsonForCreation(
        const Json::Value&, const std::vector<std::string>& pMasqueradingVector, std::string& err);
    static bool validateJsonForUpdate(const Json::Value& pJson, std::string& err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value&, const std::vector<std::string>& pMasqueradingVector, std::string& err);
    static bool validJsonOfField(
        size_t index, const std::string& fieldName, const Json::Value& pJson, std::string& err, bool isForCreation);

    /**  For column id  */
    /// Get the value of the column id, returns the default value if the column is null
    const int32_t& getValueOfId() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t>& getId() const noexcept;
    /// Set the value of the column id
    void setId(const int32_t& pId) noexcept;

    /**  For column organisation  */
    /// Get the value of the column organisation, returns the default value if the column is null
    const std::string& getValueOfOrganisation() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getOrganisation() const noexcept;
    /// Set the value of the column organisation
    void setOrganisation(const std::string& pOrganisation) noexcept;
    void setOrganisation(std::string&& pOrganisation) noexcept;

    /**  For column name  */
    /// Get the value of the column name, returns the default value if the column is null
    const std::string& getValueOfName() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getName() const noexcept;
    /// Set the value of the column name
    void setName(const std::string& pName) noexcept;
    void setName(std::string&& pName) noexcept;

    /**  For column description  */
    /// Get the value of the column description, returns the default value if the column is null
    const std::string& getValueOfDescription() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getDescription() const noexcept;
    /// Set the value of the column description
    void setDescription(const std::string& pDescription) noexcept;
    void setDescription(std::string&& pDescription) noexcept;
    void setDescriptionToNull() noexcept;

    /**  For column token  */
    /// Get the value of the column token, returns the default value if the column is null
    const std::string& getValueOfToken() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getToken() const noexcept;
    /// Set the value of the column token
    void setToken(const std::string& pToken) noexcept;
    void setToken(std::string&& pToken) noexcept;

    /**  For column token_secret_hash  */
    /// Get the value of the column token_secret_hash, returns the default value if the column is null
    const std::string& getValueOfTokenSecretHash() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getTokenSecretHash() const noexcept;
    /// Set the value of the column token_secret_hash
    void setTokenSecretHash(const std::string& pTokenSecretHash) noexcept;
    void setTokenSecretHash(std::string&& pTokenSecretHash) noexcept;

    /**  For column domain  */
    /// Get the value of the column domain, returns the default value if the column is null
    const std::string& getValueOfDomain() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getDomain() const noexcept;
    /// Set the value of the column domain
    void setDomain(const std::string& pDomain) noexcept;
    void setDomain(std::string&& pDomain) noexcept;
    void setDomainToNull() noexcept;

    /**  For column deleted_at  */
    /// Get the value of the column deleted_at, returns the default value if the column is null
    const ::trantor::Date& getValueOfDeletedAt() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date>& getDeletedAt() const noexcept;
    /// Set the value of the column deleted_at
    void setDeletedAt(const ::trantor::Date& pDeletedAt) noexcept;
    void setDeletedAtToNull() noexcept;

    /**  For column status  */
    /// Get the value of the column status, returns the default value if the column is null
    const std::string& getValueOfStatus() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getStatus() const noexcept;
    /// Set the value of the column status
    void setStatus(const std::string& pStatus) noexcept;
    void setStatus(std::string&& pStatus) noexcept;

    /**  For column metadata  */
    /// Get the value of the column metadata, returns the default value if the column is null
    const std::string& getValueOfMetadata() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getMetadata() const noexcept;
    /// Set the value of the column metadata
    void setMetadata(const std::string& pMetadata) noexcept;
    void setMetadata(std::string&& pMetadata) noexcept;

    /**  For column total_virtual_size  */
    /// Get the value of the column total_virtual_size, returns the default value if the column is null
    const int64_t& getValueOfTotalVirtualSize() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getTotalVirtualSize() const noexcept;
    /// Set the value of the column total_virtual_size
    void setTotalVirtualSize(const int64_t& pTotalVirtualSize) noexcept;

    /**  For column total_real_size  */
    /// Get the value of the column total_real_size, returns the default value if the column is null
    const int64_t& getValueOfTotalRealSize() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getTotalRealSize() const noexcept;
    /// Set the value of the column total_real_size
    void setTotalRealSize(const int64_t& pTotalRealSize) noexcept;

    /**  For column storage_limit  */
    /// Get the value of the column storage_limit, returns the default value if the column is null
    const int64_t& getValueOfStorageLimit() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getStorageLimit() const noexcept;
    /// Set the value of the column storage_limit
    void setStorageLimit(const int64_t& pStorageLimit) noexcept;
    void setStorageLimitToNull() noexcept;

    /**  For column total_entry_count  */
    /// Get the value of the column total_entry_count, returns the default value if the column is null
    const int64_t& getValueOfTotalEntryCount() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getTotalEntryCount() const noexcept;
    /// Set the value of the column total_entry_count
    void setTotalEntryCount(const int64_t& pTotalEntryCount) noexcept;

    /**  For column entry_count_limit  */
    /// Get the value of the column entry_count_limit, returns the default value if the column is null
    const int64_t& getValueOfEntryCountLimit() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getEntryCountLimit() const noexcept;
    /// Set the value of the column entry_count_limit
    void setEntryCountLimit(const int64_t& pEntryCountLimit) noexcept;
    void setEntryCountLimitToNull() noexcept;

    /**  For column created_at  */
    /// Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date& getValueOfCreatedAt() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date>& getCreatedAt() const noexcept;
    /// Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date& pCreatedAt) noexcept;

    /**  For column updated_at  */
    /// Get the value of the column updated_at, returns the default value if the column is null
    const ::trantor::Date& getValueOfUpdatedAt() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date>& getUpdatedAt() const noexcept;
    /// Set the value of the column updated_at
    void setUpdatedAt(const ::trantor::Date& pUpdatedAt) noexcept;

    static size_t getColumnNumber() noexcept {
        return 17;
    }
    static const std::string& getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string>& pMasqueradingVector) const;
    /// Relationship interfaces
private:
    friend drogon::orm::Mapper<AutomatedServices>;
    friend drogon::orm::BaseBuilder<AutomatedServices, true, true>;
    friend drogon::orm::BaseBuilder<AutomatedServices, true, false>;
    friend drogon::orm::BaseBuilder<AutomatedServices, false, true>;
    friend drogon::orm::BaseBuilder<AutomatedServices, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<AutomatedServices>;
#endif
    static const std::vector<std::string>& insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder& binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder& binder) const;
    /// For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<std::string> organisation_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<std::string> token_;
    std::shared_ptr<std::string> tokenSecretHash_;
    std::shared_ptr<std::string> domain_;
    std::shared_ptr<::trantor::Date> deletedAt_;
    std::shared_ptr<std::string> status_;
    std::shared_ptr<std::string> metadata_;
    std::shared_ptr<int64_t> totalVirtualSize_;
    std::shared_ptr<int64_t> totalRealSize_;
    std::shared_ptr<int64_t> storageLimit_;
    std::shared_ptr<int64_t> totalEntryCount_;
    std::shared_ptr<int64_t> entryCountLimit_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<::trantor::Date> updatedAt_;
    struct MetaData {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[17] = {false};

public:
    static const std::string& sqlForFindingByPrimaryKey() {
        static const std::string sql = "select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string& sqlForDeletingByPrimaryKey() {
        static const std::string sql = "delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool& needSelection) const {
        std::string sql = "insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if (dirtyFlag_[1]) {
            sql += "organisation,";
            ++parametersCount;
        }
        if (dirtyFlag_[2]) {
            sql += "name,";
            ++parametersCount;
        }
        if (dirtyFlag_[3]) {
            sql += "description,";
            ++parametersCount;
        }
        if (dirtyFlag_[4]) {
            sql += "token,";
            ++parametersCount;
        }
        if (dirtyFlag_[5]) {
            sql += "token_secret_hash,";
            ++parametersCount;
        }
        if (dirtyFlag_[6]) {
            sql += "domain,";
            ++parametersCount;
        }
        if (dirtyFlag_[7]) {
            sql += "deleted_at,";
            ++parametersCount;
        }
        sql += "status,";
        ++parametersCount;
        if (!dirtyFlag_[8]) {
            needSelection = true;
        }
        sql += "metadata,";
        ++parametersCount;
        if (!dirtyFlag_[9]) {
            needSelection = true;
        }
        sql += "total_virtual_size,";
        ++parametersCount;
        if (!dirtyFlag_[10]) {
            needSelection = true;
        }
        sql += "total_real_size,";
        ++parametersCount;
        if (!dirtyFlag_[11]) {
            needSelection = true;
        }
        if (dirtyFlag_[12]) {
            sql += "storage_limit,";
            ++parametersCount;
        }
        sql += "total_entry_count,";
        ++parametersCount;
        if (!dirtyFlag_[13]) {
            needSelection = true;
        }
        sql += "entry_count_limit,";
        ++parametersCount;
        if (!dirtyFlag_[14]) {
            needSelection = true;
        }
        sql += "created_at,";
        ++parametersCount;
        if (!dirtyFlag_[15]) {
            needSelection = true;
        }
        sql += "updated_at,";
        ++parametersCount;
        if (!dirtyFlag_[16]) {
            needSelection = true;
        }
        needSelection = true;
        if (parametersCount > 0) {
            sql[sql.length() - 1] = ')';
            sql += " values (";
        } else
            sql += ") values (";

        int placeholder = 1;
        char placeholderStr[64];
        size_t n = 0;
        sql += "default,";
        if (dirtyFlag_[1]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[2]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[3]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[4]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[5]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[6]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[7]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[8]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[9]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[10]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[11]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[12]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[13]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[14]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[15]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[16]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (parametersCount > 0) {
            sql.resize(sql.length() - 1);
        }
        if (needSelection) {
            sql.append(") returning *");
        } else {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace core
} // namespace sgrn
} // namespace drogon_model
