/**
 *
 *  Users.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/BaseBuilder.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/SqlBinder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <iostream>
#include <json/json.h>
#include <memory>
#include <stdint.h>
#include <string>
#include <string_view>
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <tuple>
#include <vector>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
} // namespace orm
} // namespace drogon
namespace drogon_model
{
namespace sgrn
{
namespace core
{

class Users {
public:
    struct Cols {
        static const std::string _id;
        static const std::string _organisation;
        static const std::string _first_name;
        static const std::string _family_name;
        static const std::string _email;
        static const std::string _password;
        static const std::string _phone_number;
        static const std::string _role;
        static const std::string _domain;
        static const std::string _deleted_at;
        static const std::string _status;
        static const std::string _is_active;
        static const std::string _can_read_personal;
        static const std::string _can_write_personal;
        static const std::string _can_delete_personal;
        static const std::string _total_virtual_size;
        static const std::string _total_real_size;
        static const std::string _storage_limit;
        static const std::string _total_entry_count;
        static const std::string _entry_count_limit;
        static const std::string _created_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType& getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Users(const drogon::orm::Row& r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Users(const Json::Value& pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Users(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false);

    Users() = default;

    void updateByJson(const Json::Value& pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value& pJson, std::string& err);
    static bool validateMasqueradedJsonForCreation(
        const Json::Value&, const std::vector<std::string>& pMasqueradingVector, std::string& err);
    static bool validateJsonForUpdate(const Json::Value& pJson, std::string& err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value&, const std::vector<std::string>& pMasqueradingVector, std::string& err);
    static bool validJsonOfField(
        size_t index, const std::string& fieldName, const Json::Value& pJson, std::string& err, bool isForCreation);

    /**  For column id  */
    /// Get the value of the column id, returns the default value if the column is null
    const int32_t& getValueOfId() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t>& getId() const noexcept;
    /// Set the value of the column id
    void setId(const int32_t& pId) noexcept;

    /**  For column organisation  */
    /// Get the value of the column organisation, returns the default value if the column is null
    const std::string& getValueOfOrganisation() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getOrganisation() const noexcept;
    /// Set the value of the column organisation
    void setOrganisation(const std::string& pOrganisation) noexcept;
    void setOrganisation(std::string&& pOrganisation) noexcept;

    /**  For column first_name  */
    /// Get the value of the column first_name, returns the default value if the column is null
    const std::string& getValueOfFirstName() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getFirstName() const noexcept;
    /// Set the value of the column first_name
    void setFirstName(const std::string& pFirstName) noexcept;
    void setFirstName(std::string&& pFirstName) noexcept;

    /**  For column family_name  */
    /// Get the value of the column family_name, returns the default value if the column is null
    const std::string& getValueOfFamilyName() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getFamilyName() const noexcept;
    /// Set the value of the column family_name
    void setFamilyName(const std::string& pFamilyName) noexcept;
    void setFamilyName(std::string&& pFamilyName) noexcept;

    /**  For column email  */
    /// Get the value of the column email, returns the default value if the column is null
    const std::string& getValueOfEmail() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getEmail() const noexcept;
    /// Set the value of the column email
    void setEmail(const std::string& pEmail) noexcept;
    void setEmail(std::string&& pEmail) noexcept;

    /**  For column password  */
    /// Get the value of the column password, returns the default value if the column is null
    const std::string& getValueOfPassword() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getPassword() const noexcept;
    /// Set the value of the column password
    void setPassword(const std::string& pPassword) noexcept;
    void setPassword(std::string&& pPassword) noexcept;

    /**  For column phone_number  */
    /// Get the value of the column phone_number, returns the default value if the column is null
    const std::string& getValueOfPhoneNumber() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getPhoneNumber() const noexcept;
    /// Set the value of the column phone_number
    void setPhoneNumber(const std::string& pPhoneNumber) noexcept;
    void setPhoneNumber(std::string&& pPhoneNumber) noexcept;
    void setPhoneNumberToNull() noexcept;

    /**  For column role  */
    /// Get the value of the column role, returns the default value if the column is null
    const std::string& getValueOfRole() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getRole() const noexcept;
    /// Set the value of the column role
    void setRole(const std::string& pRole) noexcept;
    void setRole(std::string&& pRole) noexcept;

    /**  For column domain  */
    /// Get the value of the column domain, returns the default value if the column is null
    const std::string& getValueOfDomain() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getDomain() const noexcept;
    /// Set the value of the column domain
    void setDomain(const std::string& pDomain) noexcept;
    void setDomain(std::string&& pDomain) noexcept;
    void setDomainToNull() noexcept;

    /**  For column deleted_at  */
    /// Get the value of the column deleted_at, returns the default value if the column is null
    const ::trantor::Date& getValueOfDeletedAt() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date>& getDeletedAt() const noexcept;
    /// Set the value of the column deleted_at
    void setDeletedAt(const ::trantor::Date& pDeletedAt) noexcept;
    void setDeletedAtToNull() noexcept;

    /**  For column status  */
    /// Get the value of the column status, returns the default value if the column is null
    const std::string& getValueOfStatus() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getStatus() const noexcept;
    /// Set the value of the column status
    void setStatus(const std::string& pStatus) noexcept;
    void setStatus(std::string&& pStatus) noexcept;

    /**  For column is_active  */
    /// Get the value of the column is_active, returns the default value if the column is null
    const bool& getValueOfIsActive() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool>& getIsActive() const noexcept;
    /// Set the value of the column is_active
    void setIsActive(const bool& pIsActive) noexcept;

    /**  For column can_read_personal  */
    /// Get the value of the column can_read_personal, returns the default value if the column is null
    const bool& getValueOfCanReadPersonal() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool>& getCanReadPersonal() const noexcept;
    /// Set the value of the column can_read_personal
    void setCanReadPersonal(const bool& pCanReadPersonal) noexcept;

    /**  For column can_write_personal  */
    /// Get the value of the column can_write_personal, returns the default value if the column is null
    const bool& getValueOfCanWritePersonal() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool>& getCanWritePersonal() const noexcept;
    /// Set the value of the column can_write_personal
    void setCanWritePersonal(const bool& pCanWritePersonal) noexcept;

    /**  For column can_delete_personal  */
    /// Get the value of the column can_delete_personal, returns the default value if the column is null
    const bool& getValueOfCanDeletePersonal() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool>& getCanDeletePersonal() const noexcept;
    /// Set the value of the column can_delete_personal
    void setCanDeletePersonal(const bool& pCanDeletePersonal) noexcept;

    /**  For column total_virtual_size  */
    /// Get the value of the column total_virtual_size, returns the default value if the column is null
    const int64_t& getValueOfTotalVirtualSize() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getTotalVirtualSize() const noexcept;
    /// Set the value of the column total_virtual_size
    void setTotalVirtualSize(const int64_t& pTotalVirtualSize) noexcept;

    /**  For column total_real_size  */
    /// Get the value of the column total_real_size, returns the default value if the column is null
    const int64_t& getValueOfTotalRealSize() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getTotalRealSize() const noexcept;
    /// Set the value of the column total_real_size
    void setTotalRealSize(const int64_t& pTotalRealSize) noexcept;

    /**  For column storage_limit  */
    /// Get the value of the column storage_limit, returns the default value if the column is null
    const int64_t& getValueOfStorageLimit() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getStorageLimit() const noexcept;
    /// Set the value of the column storage_limit
    void setStorageLimit(const int64_t& pStorageLimit) noexcept;
    void setStorageLimitToNull() noexcept;

    /**  For column total_entry_count  */
    /// Get the value of the column total_entry_count, returns the default value if the column is null
    const int64_t& getValueOfTotalEntryCount() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getTotalEntryCount() const noexcept;
    /// Set the value of the column total_entry_count
    void setTotalEntryCount(const int64_t& pTotalEntryCount) noexcept;

    /**  For column entry_count_limit  */
    /// Get the value of the column entry_count_limit, returns the default value if the column is null
    const int64_t& getValueOfEntryCountLimit() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getEntryCountLimit() const noexcept;
    /// Set the value of the column entry_count_limit
    void setEntryCountLimit(const int64_t& pEntryCountLimit) noexcept;
    void setEntryCountLimitToNull() noexcept;

    /**  For column created_at  */
    /// Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date& getValueOfCreatedAt() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date>& getCreatedAt() const noexcept;
    /// Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date& pCreatedAt) noexcept;

    static size_t getColumnNumber() noexcept {
        return 21;
    }
    static const std::string& getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string>& pMasqueradingVector) const;
    /// Relationship interfaces
private:
    friend drogon::orm::Mapper<Users>;
    friend drogon::orm::BaseBuilder<Users, true, true>;
    friend drogon::orm::BaseBuilder<Users, true, false>;
    friend drogon::orm::BaseBuilder<Users, false, true>;
    friend drogon::orm::BaseBuilder<Users, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Users>;
#endif
    static const std::vector<std::string>& insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder& binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder& binder) const;
    /// For mysql or sqlite3
    void updateId(const uint64_t id_);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<std::string> organisation_;
    std::shared_ptr<std::string> firstName_;
    std::shared_ptr<std::string> familyName_;
    std::shared_ptr<std::string> email_;
    std::shared_ptr<std::string> password_;
    std::shared_ptr<std::string> phoneNumber_;
    std::shared_ptr<std::string> role_;
    std::shared_ptr<std::string> domain_;
    std::shared_ptr<::trantor::Date> deletedAt_;
    std::shared_ptr<std::string> status_;
    std::shared_ptr<bool> isActive_;
    std::shared_ptr<bool> canReadPersonal_;
    std::shared_ptr<bool> canWritePersonal_;
    std::shared_ptr<bool> canDeletePersonal_;
    std::shared_ptr<int64_t> totalVirtualSize_;
    std::shared_ptr<int64_t> totalRealSize_;
    std::shared_ptr<int64_t> storageLimit_;
    std::shared_ptr<int64_t> totalEntryCount_;
    std::shared_ptr<int64_t> entryCountLimit_;
    std::shared_ptr<::trantor::Date> createdAt_;
    struct MetaData {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[21] = {false};

public:
    static const std::string& sqlForFindingByPrimaryKey() {
        static const std::string sql = "select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string& sqlForDeletingByPrimaryKey() {
        static const std::string sql = "delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool& needSelection) const {
        std::string sql = "insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if (dirtyFlag_[1]) {
            sql += "organisation,";
            ++parametersCount;
        }
        if (dirtyFlag_[2]) {
            sql += "first_name,";
            ++parametersCount;
        }
        if (dirtyFlag_[3]) {
            sql += "family_name,";
            ++parametersCount;
        }
        if (dirtyFlag_[4]) {
            sql += "email,";
            ++parametersCount;
        }
        if (dirtyFlag_[5]) {
            sql += "password,";
            ++parametersCount;
        }
        if (dirtyFlag_[6]) {
            sql += "phone_number,";
            ++parametersCount;
        }
        sql += "role,";
        ++parametersCount;
        if (!dirtyFlag_[7]) {
            needSelection = true;
        }
        if (dirtyFlag_[8]) {
            sql += "domain,";
            ++parametersCount;
        }
        if (dirtyFlag_[9]) {
            sql += "deleted_at,";
            ++parametersCount;
        }
        sql += "status,";
        ++parametersCount;
        if (!dirtyFlag_[10]) {
            needSelection = true;
        }
        sql += "is_active,";
        ++parametersCount;
        if (!dirtyFlag_[11]) {
            needSelection = true;
        }
        sql += "can_read_personal,";
        ++parametersCount;
        if (!dirtyFlag_[12]) {
            needSelection = true;
        }
        sql += "can_write_personal,";
        ++parametersCount;
        if (!dirtyFlag_[13]) {
            needSelection = true;
        }
        sql += "can_delete_personal,";
        ++parametersCount;
        if (!dirtyFlag_[14]) {
            needSelection = true;
        }
        sql += "total_virtual_size,";
        ++parametersCount;
        if (!dirtyFlag_[15]) {
            needSelection = true;
        }
        sql += "total_real_size,";
        ++parametersCount;
        if (!dirtyFlag_[16]) {
            needSelection = true;
        }
        if (dirtyFlag_[17]) {
            sql += "storage_limit,";
            ++parametersCount;
        }
        sql += "total_entry_count,";
        ++parametersCount;
        if (!dirtyFlag_[18]) {
            needSelection = true;
        }
        sql += "entry_count_limit,";
        ++parametersCount;
        if (!dirtyFlag_[19]) {
            needSelection = true;
        }
        sql += "created_at,";
        ++parametersCount;
        if (!dirtyFlag_[20]) {
            needSelection = true;
        }
        needSelection = true;
        if (parametersCount > 0) {
            sql[sql.length() - 1] = ')';
            sql += " values (";
        } else
            sql += ") values (";

        int placeholder = 1;
        char placeholderStr[64];
        size_t n = 0;
        sql += "default,";
        if (dirtyFlag_[1]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[2]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[3]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[4]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[5]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[6]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[7]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[8]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[9]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[10]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[11]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[12]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[13]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[14]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[15]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[16]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[17]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[18]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[19]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[20]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (parametersCount > 0) {
            sql.resize(sql.length() - 1);
        }
        if (needSelection) {
            sql.append(") returning *");
        } else {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace core
} // namespace sgrn
} // namespace drogon_model
