# harvest_win64.cmake — Win64 SO dependency puller
message(STATUS "[SGRN-PKG/win64] Harvesting dependencies...")
if(POLICY CMP0057)
    cmake_policy(SET CMP0057 NEW) # enable IN_LIST in if()
endif()

set(_search_dirs "${SGRN_HARVEST_SEARCH_DIRS}")
set(_to_process "${SGRN_HARVEST_EXECUTABLES};${SGRN_HARVEST_LIBRARIES}")
set(_processed "")
set(_installed "")

while(_to_process)
    list(GET _to_process 0 _current)
    list(REMOVE_AT _to_process 0)
    if("${_current}" IN_LIST _processed OR NOT EXISTS "${_current}")
        continue()
    endif()
    list(APPEND _processed "${_current}")
    execute_process(COMMAND "${SGRN_OBJDUMP}" -p "${_current}" OUTPUT_VARIABLE _dump RESULT_VARIABLE _res)
    if(NOT _res EQUAL 0)
        continue()
    endif()
    string(REGEX MATCHALL "DLL Name: [A-Za-z0-9._+-]+" _dll_lines "${_dump}")
    foreach(_line ${_dll_lines})
        string(REPLACE "DLL Name: " "" _dll_name "${_line}")
        string(TOLOWER "${_dll_name}" _dll_name_lc)
        if(_dll_name_lc MATCHES "^(kernel32|user32|gdi32|winspool|comdlg32|advapi32|shell32|ole32|oleaut32|uuid|odbc32|odbccp32|ws2_32|msvcrt|wsock32|rpcrt4|dnsapi|iphlpapi|secur32|shlwapi|winmm|userenv|bcrypt|crypt32|imm32|comctl32|mpr|netapi32|version|wldap32|winhttp)\\.dll$")
            continue()
        endif()
        set(_found "NOTFOUND")
        foreach(_dir ${_search_dirs})
            if(EXISTS "${_dir}/${_dll_name}")
                set(_found "${_dir}/${_dll_name}")
                break()
            endif()
            # Case-insensitive search fallback for Windows
            string(TOLOWER "${_dll_name}" _dll_name_lower)
            if(EXISTS "${_dir}/${_dll_name_lower}")
                set(_found "${_dir}/${_dll_name_lower}")
                break()
            endif()
        endforeach()
        if(_found)
            get_filename_component(_found_name "${_found}" NAME)
            if(NOT "${_found_name}" IN_LIST _installed)
                message(STATUS "  -> Harvesting: ${_found_name}")
                file(INSTALL "${_found}" DESTINATION "${CMAKE_INSTALL_PREFIX}")
                list(APPEND _installed "${_found_name}")
                list(APPEND _to_process "${_found}")
            endif()
        endif()
    endforeach()
endwhile()
