/**
 *
 *  Sessions.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/BaseBuilder.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/SqlBinder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <iostream>
#include <json/json.h>
#include <memory>
#include <stdint.h>
#include <string>
#include <string_view>
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <tuple>
#include <vector>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
} // namespace orm
} // namespace drogon
namespace drogon_model
{
namespace sgrn
{
namespace core
{

class Sessions {
public:
    struct Cols {
        static const std::string _id;
        static const std::string _user_id;
        static const std::string _automated_service_id;
        static const std::string _token;
        static const std::string _ip;
        static const std::string _created_at;
        static const std::string _terminated_at;
        static const std::string _termination_reason;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType& getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Sessions(const drogon::orm::Row& r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Sessions(const Json::Value& pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Sessions(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false);

    Sessions() = default;

    void updateByJson(const Json::Value& pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value& pJson, std::string& err);
    static bool validateMasqueradedJsonForCreation(
        const Json::Value&, const std::vector<std::string>& pMasqueradingVector, std::string& err);
    static bool validateJsonForUpdate(const Json::Value& pJson, std::string& err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value&, const std::vector<std::string>& pMasqueradingVector, std::string& err);
    static bool validJsonOfField(
        size_t index, const std::string& fieldName, const Json::Value& pJson, std::string& err, bool isForCreation);

    /**  For column id  */
    /// Get the value of the column id, returns the default value if the column is null
    const int64_t& getValueOfId() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getId() const noexcept;
    /// Set the value of the column id
    void setId(const int64_t& pId) noexcept;

    /**  For column user_id  */
    /// Get the value of the column user_id, returns the default value if the column is null
    const int32_t& getValueOfUserId() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t>& getUserId() const noexcept;
    /// Set the value of the column user_id
    void setUserId(const int32_t& pUserId) noexcept;
    void setUserIdToNull() noexcept;

    /**  For column automated_service_id  */
    /// Get the value of the column automated_service_id, returns the default value if the column is null
    const int32_t& getValueOfAutomatedServiceId() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t>& getAutomatedServiceId() const noexcept;
    /// Set the value of the column automated_service_id
    void setAutomatedServiceId(const int32_t& pAutomatedServiceId) noexcept;
    void setAutomatedServiceIdToNull() noexcept;

    /**  For column token  */
    /// Get the value of the column token, returns the default value if the column is null
    const std::string& getValueOfToken() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getToken() const noexcept;
    /// Set the value of the column token
    void setToken(const std::string& pToken) noexcept;
    void setToken(std::string&& pToken) noexcept;

    /**  For column ip  */
    /// Get the value of the column ip, returns the default value if the column is null
    const std::string& getValueOfIp() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getIp() const noexcept;
    /// Set the value of the column ip
    void setIp(const std::string& pIp) noexcept;
    void setIp(std::string&& pIp) noexcept;

    /**  For column created_at  */
    /// Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date& getValueOfCreatedAt() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date>& getCreatedAt() const noexcept;
    /// Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date& pCreatedAt) noexcept;

    /**  For column terminated_at  */
    /// Get the value of the column terminated_at, returns the default value if the column is null
    const ::trantor::Date& getValueOfTerminatedAt() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date>& getTerminatedAt() const noexcept;
    /// Set the value of the column terminated_at
    void setTerminatedAt(const ::trantor::Date& pTerminatedAt) noexcept;
    void setTerminatedAtToNull() noexcept;

    /**  For column termination_reason  */
    /// Get the value of the column termination_reason, returns the default value if the column is null
    const std::string& getValueOfTerminationReason() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getTerminationReason() const noexcept;
    /// Set the value of the column termination_reason
    void setTerminationReason(const std::string& pTerminationReason) noexcept;
    void setTerminationReason(std::string&& pTerminationReason) noexcept;
    void setTerminationReasonToNull() noexcept;

    static size_t getColumnNumber() noexcept {
        return 8;
    }
    static const std::string& getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string>& pMasqueradingVector) const;
    /// Relationship interfaces
private:
    friend drogon::orm::Mapper<Sessions>;
    friend drogon::orm::BaseBuilder<Sessions, true, true>;
    friend drogon::orm::BaseBuilder<Sessions, true, false>;
    friend drogon::orm::BaseBuilder<Sessions, false, true>;
    friend drogon::orm::BaseBuilder<Sessions, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Sessions>;
#endif
    static const std::vector<std::string>& insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder& binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder& binder) const;
    /// For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<int32_t> userId_;
    std::shared_ptr<int32_t> automatedServiceId_;
    std::shared_ptr<std::string> token_;
    std::shared_ptr<std::string> ip_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<::trantor::Date> terminatedAt_;
    std::shared_ptr<std::string> terminationReason_;
    struct MetaData {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[8] = {false};

public:
    static const std::string& sqlForFindingByPrimaryKey() {
        static const std::string sql = "select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string& sqlForDeletingByPrimaryKey() {
        static const std::string sql = "delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool& needSelection) const {
        std::string sql = "insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if (dirtyFlag_[1]) {
            sql += "user_id,";
            ++parametersCount;
        }
        if (dirtyFlag_[2]) {
            sql += "automated_service_id,";
            ++parametersCount;
        }
        if (dirtyFlag_[3]) {
            sql += "token,";
            ++parametersCount;
        }
        if (dirtyFlag_[4]) {
            sql += "ip,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if (!dirtyFlag_[5]) {
            needSelection = true;
        }
        if (dirtyFlag_[6]) {
            sql += "terminated_at,";
            ++parametersCount;
        }
        if (dirtyFlag_[7]) {
            sql += "termination_reason,";
            ++parametersCount;
        }
        needSelection = true;
        if (parametersCount > 0) {
            sql[sql.length() - 1] = ')';
            sql += " values (";
        } else
            sql += ") values (";

        int placeholder = 1;
        char placeholderStr[64];
        size_t n = 0;
        sql += "default,";
        if (dirtyFlag_[1]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[2]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[3]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[4]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[5]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[6]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[7]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (parametersCount > 0) {
            sql.resize(sql.length() - 1);
        }
        if (needSelection) {
            sql.append(") returning *");
        } else {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace core
} // namespace sgrn
} // namespace drogon_model
