# cmake/sgrn_datastore_core.cmake - SGRN core interface library
# This library propagates all includes, compile flags, and dependencies

# Create dummy source file if needed
if(NOT EXISTS "${PROJECT_SOURCE_DIR}/cmake/sgrn_datastore_core.cpp")
    file(WRITE "${PROJECT_SOURCE_DIR}/cmake/sgrn_datastore_core.cpp" "// Generated by CMake\n")
endif()

# ==================== SGRN Backend Core Interface Library ====================
add_library(sgrn_datastore_core INTERFACE)

# ==================== Include Directories ====================
target_include_directories(sgrn_datastore_core INTERFACE
    ${PROJECT_SOURCE_DIR}/src
)

# System includes (suppress warnings from external headers)
target_include_directories(sgrn_datastore_core SYSTEM INTERFACE
)

# ==================== Link Libraries ====================
# We link against stable sgrn::* interface targets
target_link_libraries(sgrn_datastore_core INTERFACE
    sgrn::core
    sgrn::drogon
    sgrn::trantor
    sgrn::fmt
    sgrn::jsoncpp
    sgrn::openssl
    sgrn::postgres
    sgrn::zstd
    sgrn::redis
    sgrn::utils
)

# ==================== Compiler Flags ====================
# Base warning flags
target_compile_options(sgrn_datastore_core INTERFACE
    -Wall -Wextra -Wpedantic
    -Wno-unused-parameter
    -Wno-unused-variable
)

# -fcoro-frame-pointer mitigation for Clang coroutine frame double-destructor bug
if(SGRN_COMPILER_CLANG)
    include(CheckCXXCompilerFlag)
    check_cxx_compiler_flag("-fcoro-frame-pointer" SGRN_HAS_CORO_FRAME_POINTER)
    if(SGRN_HAS_CORO_FRAME_POINTER)
        target_compile_options(sgrn_datastore_core INTERFACE -fcoro-frame-pointer)
        message(STATUS "Coroutine safety: -fcoro-frame-pointer enabled (LLVM #56493 mitigation)")
    endif()
endif()

# Conda rpath-link for runtime library resolution
if(NOT WIN32 AND DEFINED ENV{CONDA_PREFIX})
    target_link_options(sgrn_datastore_core INTERFACE
        -Wl,-rpath-link,$ENV{CONDA_PREFIX}/lib
    )
endif()

# Apply debug definitions
set(DEBUG_OPTIONS
    DEBUG_S7_GATEWAY DEBUG_S7_CORE DEBUG_S7_LAYOUT
    DEBUG_AUTH_HANDLER DEBUG_STORAGE_HANDLER DEBUG_QUERY_HANDLER
    DEBUG_GPAO_HANDLER DEBUG_ADMIN_HANDLER DEBUG_S7_HANDLER
    DEBUG_AUTH_SERVICE DEBUG_STORAGE_SERVICE DEBUG_TELEMETRY_SERVICE
    DEBUG_CONTROL_SERVICE DEBUG_ADMIN_SERVICE DEBUG_REDIS_SERVICE
    DEBUG_PLUGIN_POSTGREST DEBUG_PLUGIN_AWS_S3 DEBUG_PLUGIN_THREADPOOL
    DEBUG_UTIL_JWT DEBUG_UTIL_JSON DEBUG_UTIL_COMPRESSION
    DEBUG_UTIL_ENCODING DEBUG_UTIL_HASHING
    DEBUG_CORE_ORM DEBUG_CORE_DATABASE DEBUG_CORE_HTTP_ROUTER
    DEBUG_CORE_REDIS
)
foreach(flag ${DEBUG_OPTIONS})
    if(${flag})
        target_compile_definitions(sgrn_datastore_core INTERFACE ${flag}=1)
    endif()
endforeach()

# ==================== Sanitizers ====================
if(SANITIZE)
    target_compile_options(sgrn_datastore_core INTERFACE -fsanitize=address,undefined)
    target_link_options(sgrn_datastore_core INTERFACE -fsanitize=address,undefined)
endif()

# ==================== Release Optimizations ====================
if(RELEASE)
    target_compile_options(sgrn_datastore_core INTERFACE -O3 -DNDEBUG -flto)
    target_link_options(sgrn_datastore_core INTERFACE -flto -fuse-ld=lld)
endif()

# ==================== Helper Functions ====================
function(sgrn_target target)
    target_link_libraries(${target} PRIVATE sgrn_datastore_core)
endfunction()

function(sgrn_install_library target)
    install(TARGETS ${target}
        LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
        RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
        ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    )
endfunction()

function(sgrn_install_executable target)
    install(TARGETS ${target}
        RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
    )
endfunction()
