/**
 *
 *  Objects.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/BaseBuilder.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/SqlBinder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <iostream>
#include <json/json.h>
#include <memory>
#include <stdint.h>
#include <string>
#include <string_view>
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <tuple>
#include <vector>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
} // namespace orm
} // namespace drogon
namespace drogon_model
{
namespace sgrn
{
namespace storage
{

class Objects {
public:
    struct Cols {
        static const std::string _id;
        static const std::string _bucket;
        static const std::string _key;
        static const std::string _size;
        static const std::string _original_size;
        static const std::string _is_compressed;
        static const std::string _compression_algorithm;
        static const std::string _compression_level;
        static const std::string _provider;
        static const std::string _deleted_at;
        static const std::string _created_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType& getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Objects(const drogon::orm::Row& r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Objects(const Json::Value& pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Objects(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false);

    Objects() = default;

    void updateByJson(const Json::Value& pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value& pJson, std::string& err);
    static bool validateMasqueradedJsonForCreation(
        const Json::Value&, const std::vector<std::string>& pMasqueradingVector, std::string& err);
    static bool validateJsonForUpdate(const Json::Value& pJson, std::string& err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value&, const std::vector<std::string>& pMasqueradingVector, std::string& err);
    static bool validJsonOfField(
        size_t index, const std::string& fieldName, const Json::Value& pJson, std::string& err, bool isForCreation);

    /**  For column id  */
    /// Get the value of the column id, returns the default value if the column is null
    const int64_t& getValueOfId() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getId() const noexcept;
    /// Set the value of the column id
    void setId(const int64_t& pId) noexcept;

    /**  For column bucket  */
    /// Get the value of the column bucket, returns the default value if the column is null
    const std::string& getValueOfBucket() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getBucket() const noexcept;
    /// Set the value of the column bucket
    void setBucket(const std::string& pBucket) noexcept;
    void setBucket(std::string&& pBucket) noexcept;

    /**  For column key  */
    /// Get the value of the column key, returns the default value if the column is null
    const std::string& getValueOfKey() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getKey() const noexcept;
    /// Set the value of the column key
    void setKey(const std::string& pKey) noexcept;
    void setKey(std::string&& pKey) noexcept;

    /**  For column size  */
    /// Get the value of the column size, returns the default value if the column is null
    const int64_t& getValueOfSize() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getSize() const noexcept;
    /// Set the value of the column size
    void setSize(const int64_t& pSize) noexcept;

    /**  For column original_size  */
    /// Get the value of the column original_size, returns the default value if the column is null
    const int64_t& getValueOfOriginalSize() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t>& getOriginalSize() const noexcept;
    /// Set the value of the column original_size
    void setOriginalSize(const int64_t& pOriginalSize) noexcept;

    /**  For column is_compressed  */
    /// Get the value of the column is_compressed, returns the default value if the column is null
    const bool& getValueOfIsCompressed() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool>& getIsCompressed() const noexcept;
    /// Set the value of the column is_compressed
    void setIsCompressed(const bool& pIsCompressed) noexcept;

    /**  For column compression_algorithm  */
    /// Get the value of the column compression_algorithm, returns the default value if the column is null
    const std::string& getValueOfCompressionAlgorithm() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getCompressionAlgorithm() const noexcept;
    /// Set the value of the column compression_algorithm
    void setCompressionAlgorithm(const std::string& pCompressionAlgorithm) noexcept;
    void setCompressionAlgorithm(std::string&& pCompressionAlgorithm) noexcept;
    void setCompressionAlgorithmToNull() noexcept;

    /**  For column compression_level  */
    /// Get the value of the column compression_level, returns the default value if the column is null
    const int32_t& getValueOfCompressionLevel() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t>& getCompressionLevel() const noexcept;
    /// Set the value of the column compression_level
    void setCompressionLevel(const int32_t& pCompressionLevel) noexcept;
    void setCompressionLevelToNull() noexcept;

    /**  For column provider  */
    /// Get the value of the column provider, returns the default value if the column is null
    const std::string& getValueOfProvider() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string>& getProvider() const noexcept;
    /// Set the value of the column provider
    void setProvider(const std::string& pProvider) noexcept;
    void setProvider(std::string&& pProvider) noexcept;

    /**  For column deleted_at  */
    /// Get the value of the column deleted_at, returns the default value if the column is null
    const ::trantor::Date& getValueOfDeletedAt() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date>& getDeletedAt() const noexcept;
    /// Set the value of the column deleted_at
    void setDeletedAt(const ::trantor::Date& pDeletedAt) noexcept;
    void setDeletedAtToNull() noexcept;

    /**  For column created_at  */
    /// Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date& getValueOfCreatedAt() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date>& getCreatedAt() const noexcept;
    /// Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date& pCreatedAt) noexcept;

    static size_t getColumnNumber() noexcept {
        return 11;
    }
    static const std::string& getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string>& pMasqueradingVector) const;
    /// Relationship interfaces
private:
    friend drogon::orm::Mapper<Objects>;
    friend drogon::orm::BaseBuilder<Objects, true, true>;
    friend drogon::orm::BaseBuilder<Objects, true, false>;
    friend drogon::orm::BaseBuilder<Objects, false, true>;
    friend drogon::orm::BaseBuilder<Objects, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Objects>;
#endif
    static const std::vector<std::string>& insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder& binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder& binder) const;
    /// For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<std::string> bucket_;
    std::shared_ptr<std::string> key_;
    std::shared_ptr<int64_t> size_;
    std::shared_ptr<int64_t> originalSize_;
    std::shared_ptr<bool> isCompressed_;
    std::shared_ptr<std::string> compressionAlgorithm_;
    std::shared_ptr<int32_t> compressionLevel_;
    std::shared_ptr<std::string> provider_;
    std::shared_ptr<::trantor::Date> deletedAt_;
    std::shared_ptr<::trantor::Date> createdAt_;
    struct MetaData {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[11] = {false};

public:
    static const std::string& sqlForFindingByPrimaryKey() {
        static const std::string sql = "select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string& sqlForDeletingByPrimaryKey() {
        static const std::string sql = "delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool& needSelection) const {
        std::string sql = "insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if (dirtyFlag_[1]) {
            sql += "bucket,";
            ++parametersCount;
        }
        if (dirtyFlag_[2]) {
            sql += "key,";
            ++parametersCount;
        }
        if (dirtyFlag_[3]) {
            sql += "size,";
            ++parametersCount;
        }
        if (dirtyFlag_[4]) {
            sql += "original_size,";
            ++parametersCount;
        }
        sql += "is_compressed,";
        ++parametersCount;
        if (!dirtyFlag_[5]) {
            needSelection = true;
        }
        if (dirtyFlag_[6]) {
            sql += "compression_algorithm,";
            ++parametersCount;
        }
        if (dirtyFlag_[7]) {
            sql += "compression_level,";
            ++parametersCount;
        }
        sql += "provider,";
        ++parametersCount;
        if (!dirtyFlag_[8]) {
            needSelection = true;
        }
        if (dirtyFlag_[9]) {
            sql += "deleted_at,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if (!dirtyFlag_[10]) {
            needSelection = true;
        }
        needSelection = true;
        if (parametersCount > 0) {
            sql[sql.length() - 1] = ')';
            sql += " values (";
        } else
            sql += ") values (";

        int placeholder = 1;
        char placeholderStr[64];
        size_t n = 0;
        sql += "default,";
        if (dirtyFlag_[1]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[2]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[3]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[4]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[5]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[6]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[7]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[8]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (dirtyFlag_[9]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[10]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
            sql.append(placeholderStr, n);
        } else {
            sql += "default,";
        }
        if (parametersCount > 0) {
            sql.resize(sql.length() - 1);
        }
        if (needSelection) {
            sql.append(") returning *");
        } else {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace storage
} // namespace sgrn
} // namespace drogon_model
