/**
 *
 *  UploadChunks.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "UploadChunks.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sgrn::storage;

const std::string UploadChunks::Cols::_id = "\"id\"";
const std::string UploadChunks::Cols::_upload_id = "\"upload_id\"";
const std::string UploadChunks::Cols::_chunk_index = "\"chunk_index\"";
const std::string UploadChunks::Cols::_chunk_size = "\"chunk_size\"";
const std::string UploadChunks::Cols::_checksum = "\"checksum\"";
const std::string UploadChunks::Cols::_storage_key = "\"storage_key\"";
const std::string UploadChunks::Cols::_object_id = "\"object_id\"";
const std::string UploadChunks::Cols::_compressed_size = "\"compressed_size\"";
const std::string UploadChunks::Cols::_created_at = "\"created_at\"";
const std::string UploadChunks::primaryKeyName = "id";
const bool UploadChunks::hasPrimaryKey = true;
const std::string UploadChunks::tableName = "storage.\"upload_chunks\"";

const std::vector<typename UploadChunks::MetaData> UploadChunks::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"upload_id","std::string","text",0,0,0,1},
{"chunk_index","int32_t","integer",4,0,0,1},
{"chunk_size","int64_t","bigint",8,0,0,1},
{"checksum","std::string","text",0,0,0,0},
{"storage_key","std::string","text",0,0,0,1},
{"object_id","int64_t","bigint",8,0,0,0},
{"compressed_size","int64_t","bigint",8,0,0,0},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,1}
};
const std::string &UploadChunks::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
UploadChunks::UploadChunks(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["upload_id"].isNull())
        {
            uploadId_=std::make_shared<std::string>(r["upload_id"].as<std::string>());
        }
        if(!r["chunk_index"].isNull())
        {
            chunkIndex_=std::make_shared<int32_t>(r["chunk_index"].as<int32_t>());
        }
        if(!r["chunk_size"].isNull())
        {
            chunkSize_=std::make_shared<int64_t>(r["chunk_size"].as<int64_t>());
        }
        if(!r["checksum"].isNull())
        {
            checksum_=std::make_shared<std::string>(r["checksum"].as<std::string>());
        }
        if(!r["storage_key"].isNull())
        {
            storageKey_=std::make_shared<std::string>(r["storage_key"].as<std::string>());
        }
        if(!r["object_id"].isNull())
        {
            objectId_=std::make_shared<int64_t>(r["object_id"].as<int64_t>());
        }
        if(!r["compressed_size"].isNull())
        {
            compressedSize_=std::make_shared<int64_t>(r["compressed_size"].as<int64_t>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            uploadId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            chunkIndex_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            chunkSize_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            checksum_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            storageKey_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            objectId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            compressedSize_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

UploadChunks::UploadChunks(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uploadId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            chunkIndex_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            chunkSize_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            checksum_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            storageKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            objectId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            compressedSize_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

UploadChunks::UploadChunks(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("upload_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["upload_id"].isNull())
        {
            uploadId_=std::make_shared<std::string>(pJson["upload_id"].asString());
        }
    }
    if(pJson.isMember("chunk_index"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["chunk_index"].isNull())
        {
            chunkIndex_=std::make_shared<int32_t>((int32_t)pJson["chunk_index"].asInt64());
        }
    }
    if(pJson.isMember("chunk_size"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["chunk_size"].isNull())
        {
            chunkSize_=std::make_shared<int64_t>((int64_t)pJson["chunk_size"].asInt64());
        }
    }
    if(pJson.isMember("checksum"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["checksum"].isNull())
        {
            checksum_=std::make_shared<std::string>(pJson["checksum"].asString());
        }
    }
    if(pJson.isMember("storage_key"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["storage_key"].isNull())
        {
            storageKey_=std::make_shared<std::string>(pJson["storage_key"].asString());
        }
    }
    if(pJson.isMember("object_id"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["object_id"].isNull())
        {
            objectId_=std::make_shared<int64_t>((int64_t)pJson["object_id"].asInt64());
        }
    }
    if(pJson.isMember("compressed_size"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["compressed_size"].isNull())
        {
            compressedSize_=std::make_shared<int64_t>((int64_t)pJson["compressed_size"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UploadChunks::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            uploadId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            chunkIndex_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            chunkSize_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            checksum_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            storageKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            objectId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            compressedSize_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UploadChunks::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("upload_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["upload_id"].isNull())
        {
            uploadId_=std::make_shared<std::string>(pJson["upload_id"].asString());
        }
    }
    if(pJson.isMember("chunk_index"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["chunk_index"].isNull())
        {
            chunkIndex_=std::make_shared<int32_t>((int32_t)pJson["chunk_index"].asInt64());
        }
    }
    if(pJson.isMember("chunk_size"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["chunk_size"].isNull())
        {
            chunkSize_=std::make_shared<int64_t>((int64_t)pJson["chunk_size"].asInt64());
        }
    }
    if(pJson.isMember("checksum"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["checksum"].isNull())
        {
            checksum_=std::make_shared<std::string>(pJson["checksum"].asString());
        }
    }
    if(pJson.isMember("storage_key"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["storage_key"].isNull())
        {
            storageKey_=std::make_shared<std::string>(pJson["storage_key"].asString());
        }
    }
    if(pJson.isMember("object_id"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["object_id"].isNull())
        {
            objectId_=std::make_shared<int64_t>((int64_t)pJson["object_id"].asInt64());
        }
    }
    if(pJson.isMember("compressed_size"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["compressed_size"].isNull())
        {
            compressedSize_=std::make_shared<int64_t>((int64_t)pJson["compressed_size"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &UploadChunks::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &UploadChunks::getId() const noexcept
{
    return id_;
}
void UploadChunks::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename UploadChunks::PrimaryKeyType & UploadChunks::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &UploadChunks::getValueOfUploadId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(uploadId_)
        return *uploadId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UploadChunks::getUploadId() const noexcept
{
    return uploadId_;
}
void UploadChunks::setUploadId(const std::string &pUploadId) noexcept
{
    uploadId_ = std::make_shared<std::string>(pUploadId);
    dirtyFlag_[1] = true;
}
void UploadChunks::setUploadId(std::string &&pUploadId) noexcept
{
    uploadId_ = std::make_shared<std::string>(std::move(pUploadId));
    dirtyFlag_[1] = true;
}

const int32_t &UploadChunks::getValueOfChunkIndex() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(chunkIndex_)
        return *chunkIndex_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UploadChunks::getChunkIndex() const noexcept
{
    return chunkIndex_;
}
void UploadChunks::setChunkIndex(const int32_t &pChunkIndex) noexcept
{
    chunkIndex_ = std::make_shared<int32_t>(pChunkIndex);
    dirtyFlag_[2] = true;
}

const int64_t &UploadChunks::getValueOfChunkSize() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(chunkSize_)
        return *chunkSize_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &UploadChunks::getChunkSize() const noexcept
{
    return chunkSize_;
}
void UploadChunks::setChunkSize(const int64_t &pChunkSize) noexcept
{
    chunkSize_ = std::make_shared<int64_t>(pChunkSize);
    dirtyFlag_[3] = true;
}

const std::string &UploadChunks::getValueOfChecksum() const noexcept
{
    static const std::string defaultValue = std::string();
    if(checksum_)
        return *checksum_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UploadChunks::getChecksum() const noexcept
{
    return checksum_;
}
void UploadChunks::setChecksum(const std::string &pChecksum) noexcept
{
    checksum_ = std::make_shared<std::string>(pChecksum);
    dirtyFlag_[4] = true;
}
void UploadChunks::setChecksum(std::string &&pChecksum) noexcept
{
    checksum_ = std::make_shared<std::string>(std::move(pChecksum));
    dirtyFlag_[4] = true;
}
void UploadChunks::setChecksumToNull() noexcept
{
    checksum_.reset();
    dirtyFlag_[4] = true;
}

const std::string &UploadChunks::getValueOfStorageKey() const noexcept
{
    static const std::string defaultValue = std::string();
    if(storageKey_)
        return *storageKey_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UploadChunks::getStorageKey() const noexcept
{
    return storageKey_;
}
void UploadChunks::setStorageKey(const std::string &pStorageKey) noexcept
{
    storageKey_ = std::make_shared<std::string>(pStorageKey);
    dirtyFlag_[5] = true;
}
void UploadChunks::setStorageKey(std::string &&pStorageKey) noexcept
{
    storageKey_ = std::make_shared<std::string>(std::move(pStorageKey));
    dirtyFlag_[5] = true;
}

const int64_t &UploadChunks::getValueOfObjectId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(objectId_)
        return *objectId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &UploadChunks::getObjectId() const noexcept
{
    return objectId_;
}
void UploadChunks::setObjectId(const int64_t &pObjectId) noexcept
{
    objectId_ = std::make_shared<int64_t>(pObjectId);
    dirtyFlag_[6] = true;
}
void UploadChunks::setObjectIdToNull() noexcept
{
    objectId_.reset();
    dirtyFlag_[6] = true;
}

const int64_t &UploadChunks::getValueOfCompressedSize() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(compressedSize_)
        return *compressedSize_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &UploadChunks::getCompressedSize() const noexcept
{
    return compressedSize_;
}
void UploadChunks::setCompressedSize(const int64_t &pCompressedSize) noexcept
{
    compressedSize_ = std::make_shared<int64_t>(pCompressedSize);
    dirtyFlag_[7] = true;
}
void UploadChunks::setCompressedSizeToNull() noexcept
{
    compressedSize_.reset();
    dirtyFlag_[7] = true;
}

const ::trantor::Date &UploadChunks::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UploadChunks::getCreatedAt() const noexcept
{
    return createdAt_;
}
void UploadChunks::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[8] = true;
}

void UploadChunks::updateId(const uint64_t id)
{
}

const std::vector<std::string> &UploadChunks::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "upload_id",
        "chunk_index",
        "chunk_size",
        "checksum",
        "storage_key",
        "object_id",
        "compressed_size",
        "created_at"
    };
    return inCols;
}

void UploadChunks::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUploadId())
        {
            binder << getValueOfUploadId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getChunkIndex())
        {
            binder << getValueOfChunkIndex();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getChunkSize())
        {
            binder << getValueOfChunkSize();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getChecksum())
        {
            binder << getValueOfChecksum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStorageKey())
        {
            binder << getValueOfStorageKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getObjectId())
        {
            binder << getValueOfObjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCompressedSize())
        {
            binder << getValueOfCompressedSize();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> UploadChunks::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void UploadChunks::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUploadId())
        {
            binder << getValueOfUploadId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getChunkIndex())
        {
            binder << getValueOfChunkIndex();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getChunkSize())
        {
            binder << getValueOfChunkSize();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getChecksum())
        {
            binder << getValueOfChecksum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStorageKey())
        {
            binder << getValueOfStorageKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getObjectId())
        {
            binder << getValueOfObjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCompressedSize())
        {
            binder << getValueOfCompressedSize();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value UploadChunks::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUploadId())
    {
        ret["upload_id"]=getValueOfUploadId();
    }
    else
    {
        ret["upload_id"]=Json::Value();
    }
    if(getChunkIndex())
    {
        ret["chunk_index"]=getValueOfChunkIndex();
    }
    else
    {
        ret["chunk_index"]=Json::Value();
    }
    if(getChunkSize())
    {
        ret["chunk_size"]=(Json::Int64)getValueOfChunkSize();
    }
    else
    {
        ret["chunk_size"]=Json::Value();
    }
    if(getChecksum())
    {
        ret["checksum"]=getValueOfChecksum();
    }
    else
    {
        ret["checksum"]=Json::Value();
    }
    if(getStorageKey())
    {
        ret["storage_key"]=getValueOfStorageKey();
    }
    else
    {
        ret["storage_key"]=Json::Value();
    }
    if(getObjectId())
    {
        ret["object_id"]=(Json::Int64)getValueOfObjectId();
    }
    else
    {
        ret["object_id"]=Json::Value();
    }
    if(getCompressedSize())
    {
        ret["compressed_size"]=(Json::Int64)getValueOfCompressedSize();
    }
    else
    {
        ret["compressed_size"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string UploadChunks::toString() const
{
    return toJson().toStyledString();
}

Json::Value UploadChunks::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUploadId())
            {
                ret[pMasqueradingVector[1]]=getValueOfUploadId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getChunkIndex())
            {
                ret[pMasqueradingVector[2]]=getValueOfChunkIndex();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getChunkSize())
            {
                ret[pMasqueradingVector[3]]=(Json::Int64)getValueOfChunkSize();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getChecksum())
            {
                ret[pMasqueradingVector[4]]=getValueOfChecksum();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getStorageKey())
            {
                ret[pMasqueradingVector[5]]=getValueOfStorageKey();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getObjectId())
            {
                ret[pMasqueradingVector[6]]=(Json::Int64)getValueOfObjectId();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCompressedSize())
            {
                ret[pMasqueradingVector[7]]=(Json::Int64)getValueOfCompressedSize();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[8]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUploadId())
    {
        ret["upload_id"]=getValueOfUploadId();
    }
    else
    {
        ret["upload_id"]=Json::Value();
    }
    if(getChunkIndex())
    {
        ret["chunk_index"]=getValueOfChunkIndex();
    }
    else
    {
        ret["chunk_index"]=Json::Value();
    }
    if(getChunkSize())
    {
        ret["chunk_size"]=(Json::Int64)getValueOfChunkSize();
    }
    else
    {
        ret["chunk_size"]=Json::Value();
    }
    if(getChecksum())
    {
        ret["checksum"]=getValueOfChecksum();
    }
    else
    {
        ret["checksum"]=Json::Value();
    }
    if(getStorageKey())
    {
        ret["storage_key"]=getValueOfStorageKey();
    }
    else
    {
        ret["storage_key"]=Json::Value();
    }
    if(getObjectId())
    {
        ret["object_id"]=(Json::Int64)getValueOfObjectId();
    }
    else
    {
        ret["object_id"]=Json::Value();
    }
    if(getCompressedSize())
    {
        ret["compressed_size"]=(Json::Int64)getValueOfCompressedSize();
    }
    else
    {
        ret["compressed_size"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool UploadChunks::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("upload_id"))
    {
        if(!validJsonOfField(1, "upload_id", pJson["upload_id"], err, true))
            return false;
    }
    else
    {
        err="The upload_id column cannot be null";
        return false;
    }
    if(pJson.isMember("chunk_index"))
    {
        if(!validJsonOfField(2, "chunk_index", pJson["chunk_index"], err, true))
            return false;
    }
    else
    {
        err="The chunk_index column cannot be null";
        return false;
    }
    if(pJson.isMember("chunk_size"))
    {
        if(!validJsonOfField(3, "chunk_size", pJson["chunk_size"], err, true))
            return false;
    }
    else
    {
        err="The chunk_size column cannot be null";
        return false;
    }
    if(pJson.isMember("checksum"))
    {
        if(!validJsonOfField(4, "checksum", pJson["checksum"], err, true))
            return false;
    }
    if(pJson.isMember("storage_key"))
    {
        if(!validJsonOfField(5, "storage_key", pJson["storage_key"], err, true))
            return false;
    }
    else
    {
        err="The storage_key column cannot be null";
        return false;
    }
    if(pJson.isMember("object_id"))
    {
        if(!validJsonOfField(6, "object_id", pJson["object_id"], err, true))
            return false;
    }
    if(pJson.isMember("compressed_size"))
    {
        if(!validJsonOfField(7, "compressed_size", pJson["compressed_size"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(8, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool UploadChunks::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UploadChunks::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("upload_id"))
    {
        if(!validJsonOfField(1, "upload_id", pJson["upload_id"], err, false))
            return false;
    }
    if(pJson.isMember("chunk_index"))
    {
        if(!validJsonOfField(2, "chunk_index", pJson["chunk_index"], err, false))
            return false;
    }
    if(pJson.isMember("chunk_size"))
    {
        if(!validJsonOfField(3, "chunk_size", pJson["chunk_size"], err, false))
            return false;
    }
    if(pJson.isMember("checksum"))
    {
        if(!validJsonOfField(4, "checksum", pJson["checksum"], err, false))
            return false;
    }
    if(pJson.isMember("storage_key"))
    {
        if(!validJsonOfField(5, "storage_key", pJson["storage_key"], err, false))
            return false;
    }
    if(pJson.isMember("object_id"))
    {
        if(!validJsonOfField(6, "object_id", pJson["object_id"], err, false))
            return false;
    }
    if(pJson.isMember("compressed_size"))
    {
        if(!validJsonOfField(7, "compressed_size", pJson["compressed_size"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(8, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool UploadChunks::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UploadChunks::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
