/**
 *
 *  UploadSessions.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "UploadSessions.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sgrn::storage;

const std::string UploadSessions::Cols::_id = "\"id\"";
const std::string UploadSessions::Cols::_user_id = "\"user_id\"";
const std::string UploadSessions::Cols::_automated_service_id = "\"automated_service_id\"";
const std::string UploadSessions::Cols::_domain = "\"domain\"";
const std::string UploadSessions::Cols::_target_path = "\"target_path\"";
const std::string UploadSessions::Cols::_filename = "\"filename\"";
const std::string UploadSessions::Cols::_mime_type = "\"mime_type\"";
const std::string UploadSessions::Cols::_total_size = "\"total_size\"";
const std::string UploadSessions::Cols::_chunk_size = "\"chunk_size\"";
const std::string UploadSessions::Cols::_total_chunks = "\"total_chunks\"";
const std::string UploadSessions::Cols::_uploaded_chunks_count = "\"uploaded_chunks_count\"";
const std::string UploadSessions::Cols::_status = "\"status\"";
const std::string UploadSessions::Cols::_file_hash = "\"file_hash\"";
const std::string UploadSessions::Cols::_compressed_size = "\"compressed_size\"";
const std::string UploadSessions::Cols::_created_at = "\"created_at\"";
const std::string UploadSessions::Cols::_updated_at = "\"updated_at\"";
const std::string UploadSessions::Cols::_expires_at = "\"expires_at\"";
const std::string UploadSessions::primaryKeyName = "id";
const bool UploadSessions::hasPrimaryKey = true;
const std::string UploadSessions::tableName = "storage.\"upload_sessions\"";

const std::vector<typename UploadSessions::MetaData> UploadSessions::metaData_={
{"id","std::string","text",0,0,1,1},
{"user_id","int32_t","integer",4,0,0,0},
{"automated_service_id","int32_t","integer",4,0,0,0},
{"domain","std::string","text",0,0,0,0},
{"target_path","std::string","text",0,0,0,1},
{"filename","std::string","text",0,0,0,1},
{"mime_type","std::string","text",0,0,0,1},
{"total_size","int64_t","bigint",8,0,0,1},
{"chunk_size","int64_t","bigint",8,0,0,1},
{"total_chunks","int32_t","integer",4,0,0,1},
{"uploaded_chunks_count","int32_t","integer",4,0,0,1},
{"status","std::string","text",0,0,0,1},
{"file_hash","std::string","text",0,0,0,0},
{"compressed_size","int64_t","bigint",8,0,0,0},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"updated_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"expires_at","::trantor::Date","timestamp with time zone",0,0,0,1}
};
const std::string &UploadSessions::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
UploadSessions::UploadSessions(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>(r["user_id"].as<int32_t>());
        }
        if(!r["automated_service_id"].isNull())
        {
            automatedServiceId_=std::make_shared<int32_t>(r["automated_service_id"].as<int32_t>());
        }
        if(!r["domain"].isNull())
        {
            domain_=std::make_shared<std::string>(r["domain"].as<std::string>());
        }
        if(!r["target_path"].isNull())
        {
            targetPath_=std::make_shared<std::string>(r["target_path"].as<std::string>());
        }
        if(!r["filename"].isNull())
        {
            filename_=std::make_shared<std::string>(r["filename"].as<std::string>());
        }
        if(!r["mime_type"].isNull())
        {
            mimeType_=std::make_shared<std::string>(r["mime_type"].as<std::string>());
        }
        if(!r["total_size"].isNull())
        {
            totalSize_=std::make_shared<int64_t>(r["total_size"].as<int64_t>());
        }
        if(!r["chunk_size"].isNull())
        {
            chunkSize_=std::make_shared<int64_t>(r["chunk_size"].as<int64_t>());
        }
        if(!r["total_chunks"].isNull())
        {
            totalChunks_=std::make_shared<int32_t>(r["total_chunks"].as<int32_t>());
        }
        if(!r["uploaded_chunks_count"].isNull())
        {
            uploadedChunksCount_=std::make_shared<int32_t>(r["uploaded_chunks_count"].as<int32_t>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
        if(!r["file_hash"].isNull())
        {
            fileHash_=std::make_shared<std::string>(r["file_hash"].as<std::string>());
        }
        if(!r["compressed_size"].isNull())
        {
            compressedSize_=std::make_shared<int64_t>(r["compressed_size"].as<int64_t>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["updated_at"].isNull())
        {
            auto timeStr = r["updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["expires_at"].isNull())
        {
            auto timeStr = r["expires_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 17 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            automatedServiceId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            domain_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            targetPath_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            filename_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            mimeType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            totalSize_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            chunkSize_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            totalChunks_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            uploadedChunksCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            fileHash_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            compressedSize_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 14;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 15;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 16;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

UploadSessions::UploadSessions(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 17)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            automatedServiceId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            domain_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            targetPath_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            filename_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            mimeType_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            totalSize_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            chunkSize_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            totalChunks_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            uploadedChunksCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            fileHash_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            compressedSize_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[13]].asInt64());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[14]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
    {
        dirtyFlag_[15] = true;
        if(!pJson[pMasqueradingVector[15]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[15]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[16].empty() && pJson.isMember(pMasqueradingVector[16]))
    {
        dirtyFlag_[16] = true;
        if(!pJson[pMasqueradingVector[16]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[16]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

UploadSessions::UploadSessions(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("automated_service_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["automated_service_id"].isNull())
        {
            automatedServiceId_=std::make_shared<int32_t>((int32_t)pJson["automated_service_id"].asInt64());
        }
    }
    if(pJson.isMember("domain"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["domain"].isNull())
        {
            domain_=std::make_shared<std::string>(pJson["domain"].asString());
        }
    }
    if(pJson.isMember("target_path"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["target_path"].isNull())
        {
            targetPath_=std::make_shared<std::string>(pJson["target_path"].asString());
        }
    }
    if(pJson.isMember("filename"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["filename"].isNull())
        {
            filename_=std::make_shared<std::string>(pJson["filename"].asString());
        }
    }
    if(pJson.isMember("mime_type"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["mime_type"].isNull())
        {
            mimeType_=std::make_shared<std::string>(pJson["mime_type"].asString());
        }
    }
    if(pJson.isMember("total_size"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["total_size"].isNull())
        {
            totalSize_=std::make_shared<int64_t>((int64_t)pJson["total_size"].asInt64());
        }
    }
    if(pJson.isMember("chunk_size"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["chunk_size"].isNull())
        {
            chunkSize_=std::make_shared<int64_t>((int64_t)pJson["chunk_size"].asInt64());
        }
    }
    if(pJson.isMember("total_chunks"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["total_chunks"].isNull())
        {
            totalChunks_=std::make_shared<int32_t>((int32_t)pJson["total_chunks"].asInt64());
        }
    }
    if(pJson.isMember("uploaded_chunks_count"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["uploaded_chunks_count"].isNull())
        {
            uploadedChunksCount_=std::make_shared<int32_t>((int32_t)pJson["uploaded_chunks_count"].asInt64());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("file_hash"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["file_hash"].isNull())
        {
            fileHash_=std::make_shared<std::string>(pJson["file_hash"].asString());
        }
    }
    if(pJson.isMember("compressed_size"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["compressed_size"].isNull())
        {
            compressedSize_=std::make_shared<int64_t>((int64_t)pJson["compressed_size"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[14]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[15]=true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[16]=true;
        if(!pJson["expires_at"].isNull())
        {
            auto timeStr = pJson["expires_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UploadSessions::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 17)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            automatedServiceId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            domain_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            targetPath_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            filename_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            mimeType_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            totalSize_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            chunkSize_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            totalChunks_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            uploadedChunksCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            fileHash_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            compressedSize_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[13]].asInt64());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[14]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
    {
        dirtyFlag_[15] = true;
        if(!pJson[pMasqueradingVector[15]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[15]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[16].empty() && pJson.isMember(pMasqueradingVector[16]))
    {
        dirtyFlag_[16] = true;
        if(!pJson[pMasqueradingVector[16]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[16]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UploadSessions::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("automated_service_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["automated_service_id"].isNull())
        {
            automatedServiceId_=std::make_shared<int32_t>((int32_t)pJson["automated_service_id"].asInt64());
        }
    }
    if(pJson.isMember("domain"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["domain"].isNull())
        {
            domain_=std::make_shared<std::string>(pJson["domain"].asString());
        }
    }
    if(pJson.isMember("target_path"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["target_path"].isNull())
        {
            targetPath_=std::make_shared<std::string>(pJson["target_path"].asString());
        }
    }
    if(pJson.isMember("filename"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["filename"].isNull())
        {
            filename_=std::make_shared<std::string>(pJson["filename"].asString());
        }
    }
    if(pJson.isMember("mime_type"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["mime_type"].isNull())
        {
            mimeType_=std::make_shared<std::string>(pJson["mime_type"].asString());
        }
    }
    if(pJson.isMember("total_size"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["total_size"].isNull())
        {
            totalSize_=std::make_shared<int64_t>((int64_t)pJson["total_size"].asInt64());
        }
    }
    if(pJson.isMember("chunk_size"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["chunk_size"].isNull())
        {
            chunkSize_=std::make_shared<int64_t>((int64_t)pJson["chunk_size"].asInt64());
        }
    }
    if(pJson.isMember("total_chunks"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["total_chunks"].isNull())
        {
            totalChunks_=std::make_shared<int32_t>((int32_t)pJson["total_chunks"].asInt64());
        }
    }
    if(pJson.isMember("uploaded_chunks_count"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["uploaded_chunks_count"].isNull())
        {
            uploadedChunksCount_=std::make_shared<int32_t>((int32_t)pJson["uploaded_chunks_count"].asInt64());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("file_hash"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["file_hash"].isNull())
        {
            fileHash_=std::make_shared<std::string>(pJson["file_hash"].asString());
        }
    }
    if(pJson.isMember("compressed_size"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["compressed_size"].isNull())
        {
            compressedSize_=std::make_shared<int64_t>((int64_t)pJson["compressed_size"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[14] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[15] = true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[16] = true;
        if(!pJson["expires_at"].isNull())
        {
            auto timeStr = pJson["expires_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &UploadSessions::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UploadSessions::getId() const noexcept
{
    return id_;
}
void UploadSessions::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void UploadSessions::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename UploadSessions::PrimaryKeyType & UploadSessions::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &UploadSessions::getValueOfUserId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UploadSessions::getUserId() const noexcept
{
    return userId_;
}
void UploadSessions::setUserId(const int32_t &pUserId) noexcept
{
    userId_ = std::make_shared<int32_t>(pUserId);
    dirtyFlag_[1] = true;
}
void UploadSessions::setUserIdToNull() noexcept
{
    userId_.reset();
    dirtyFlag_[1] = true;
}

const int32_t &UploadSessions::getValueOfAutomatedServiceId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(automatedServiceId_)
        return *automatedServiceId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UploadSessions::getAutomatedServiceId() const noexcept
{
    return automatedServiceId_;
}
void UploadSessions::setAutomatedServiceId(const int32_t &pAutomatedServiceId) noexcept
{
    automatedServiceId_ = std::make_shared<int32_t>(pAutomatedServiceId);
    dirtyFlag_[2] = true;
}
void UploadSessions::setAutomatedServiceIdToNull() noexcept
{
    automatedServiceId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &UploadSessions::getValueOfDomain() const noexcept
{
    static const std::string defaultValue = std::string();
    if(domain_)
        return *domain_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UploadSessions::getDomain() const noexcept
{
    return domain_;
}
void UploadSessions::setDomain(const std::string &pDomain) noexcept
{
    domain_ = std::make_shared<std::string>(pDomain);
    dirtyFlag_[3] = true;
}
void UploadSessions::setDomain(std::string &&pDomain) noexcept
{
    domain_ = std::make_shared<std::string>(std::move(pDomain));
    dirtyFlag_[3] = true;
}
void UploadSessions::setDomainToNull() noexcept
{
    domain_.reset();
    dirtyFlag_[3] = true;
}

const std::string &UploadSessions::getValueOfTargetPath() const noexcept
{
    static const std::string defaultValue = std::string();
    if(targetPath_)
        return *targetPath_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UploadSessions::getTargetPath() const noexcept
{
    return targetPath_;
}
void UploadSessions::setTargetPath(const std::string &pTargetPath) noexcept
{
    targetPath_ = std::make_shared<std::string>(pTargetPath);
    dirtyFlag_[4] = true;
}
void UploadSessions::setTargetPath(std::string &&pTargetPath) noexcept
{
    targetPath_ = std::make_shared<std::string>(std::move(pTargetPath));
    dirtyFlag_[4] = true;
}

const std::string &UploadSessions::getValueOfFilename() const noexcept
{
    static const std::string defaultValue = std::string();
    if(filename_)
        return *filename_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UploadSessions::getFilename() const noexcept
{
    return filename_;
}
void UploadSessions::setFilename(const std::string &pFilename) noexcept
{
    filename_ = std::make_shared<std::string>(pFilename);
    dirtyFlag_[5] = true;
}
void UploadSessions::setFilename(std::string &&pFilename) noexcept
{
    filename_ = std::make_shared<std::string>(std::move(pFilename));
    dirtyFlag_[5] = true;
}

const std::string &UploadSessions::getValueOfMimeType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(mimeType_)
        return *mimeType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UploadSessions::getMimeType() const noexcept
{
    return mimeType_;
}
void UploadSessions::setMimeType(const std::string &pMimeType) noexcept
{
    mimeType_ = std::make_shared<std::string>(pMimeType);
    dirtyFlag_[6] = true;
}
void UploadSessions::setMimeType(std::string &&pMimeType) noexcept
{
    mimeType_ = std::make_shared<std::string>(std::move(pMimeType));
    dirtyFlag_[6] = true;
}

const int64_t &UploadSessions::getValueOfTotalSize() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(totalSize_)
        return *totalSize_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &UploadSessions::getTotalSize() const noexcept
{
    return totalSize_;
}
void UploadSessions::setTotalSize(const int64_t &pTotalSize) noexcept
{
    totalSize_ = std::make_shared<int64_t>(pTotalSize);
    dirtyFlag_[7] = true;
}

const int64_t &UploadSessions::getValueOfChunkSize() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(chunkSize_)
        return *chunkSize_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &UploadSessions::getChunkSize() const noexcept
{
    return chunkSize_;
}
void UploadSessions::setChunkSize(const int64_t &pChunkSize) noexcept
{
    chunkSize_ = std::make_shared<int64_t>(pChunkSize);
    dirtyFlag_[8] = true;
}

const int32_t &UploadSessions::getValueOfTotalChunks() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(totalChunks_)
        return *totalChunks_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UploadSessions::getTotalChunks() const noexcept
{
    return totalChunks_;
}
void UploadSessions::setTotalChunks(const int32_t &pTotalChunks) noexcept
{
    totalChunks_ = std::make_shared<int32_t>(pTotalChunks);
    dirtyFlag_[9] = true;
}

const int32_t &UploadSessions::getValueOfUploadedChunksCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(uploadedChunksCount_)
        return *uploadedChunksCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UploadSessions::getUploadedChunksCount() const noexcept
{
    return uploadedChunksCount_;
}
void UploadSessions::setUploadedChunksCount(const int32_t &pUploadedChunksCount) noexcept
{
    uploadedChunksCount_ = std::make_shared<int32_t>(pUploadedChunksCount);
    dirtyFlag_[10] = true;
}

const std::string &UploadSessions::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UploadSessions::getStatus() const noexcept
{
    return status_;
}
void UploadSessions::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[11] = true;
}
void UploadSessions::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[11] = true;
}

const std::string &UploadSessions::getValueOfFileHash() const noexcept
{
    static const std::string defaultValue = std::string();
    if(fileHash_)
        return *fileHash_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UploadSessions::getFileHash() const noexcept
{
    return fileHash_;
}
void UploadSessions::setFileHash(const std::string &pFileHash) noexcept
{
    fileHash_ = std::make_shared<std::string>(pFileHash);
    dirtyFlag_[12] = true;
}
void UploadSessions::setFileHash(std::string &&pFileHash) noexcept
{
    fileHash_ = std::make_shared<std::string>(std::move(pFileHash));
    dirtyFlag_[12] = true;
}
void UploadSessions::setFileHashToNull() noexcept
{
    fileHash_.reset();
    dirtyFlag_[12] = true;
}

const int64_t &UploadSessions::getValueOfCompressedSize() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(compressedSize_)
        return *compressedSize_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &UploadSessions::getCompressedSize() const noexcept
{
    return compressedSize_;
}
void UploadSessions::setCompressedSize(const int64_t &pCompressedSize) noexcept
{
    compressedSize_ = std::make_shared<int64_t>(pCompressedSize);
    dirtyFlag_[13] = true;
}
void UploadSessions::setCompressedSizeToNull() noexcept
{
    compressedSize_.reset();
    dirtyFlag_[13] = true;
}

const ::trantor::Date &UploadSessions::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UploadSessions::getCreatedAt() const noexcept
{
    return createdAt_;
}
void UploadSessions::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[14] = true;
}

const ::trantor::Date &UploadSessions::getValueOfUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedAt_)
        return *updatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UploadSessions::getUpdatedAt() const noexcept
{
    return updatedAt_;
}
void UploadSessions::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept
{
    updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
    dirtyFlag_[15] = true;
}

const ::trantor::Date &UploadSessions::getValueOfExpiresAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(expiresAt_)
        return *expiresAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UploadSessions::getExpiresAt() const noexcept
{
    return expiresAt_;
}
void UploadSessions::setExpiresAt(const ::trantor::Date &pExpiresAt) noexcept
{
    expiresAt_ = std::make_shared<::trantor::Date>(pExpiresAt);
    dirtyFlag_[16] = true;
}

void UploadSessions::updateId(const uint64_t id)
{
}

const std::vector<std::string> &UploadSessions::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "user_id",
        "automated_service_id",
        "domain",
        "target_path",
        "filename",
        "mime_type",
        "total_size",
        "chunk_size",
        "total_chunks",
        "uploaded_chunks_count",
        "status",
        "file_hash",
        "compressed_size",
        "created_at",
        "updated_at",
        "expires_at"
    };
    return inCols;
}

void UploadSessions::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAutomatedServiceId())
        {
            binder << getValueOfAutomatedServiceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDomain())
        {
            binder << getValueOfDomain();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTargetPath())
        {
            binder << getValueOfTargetPath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getFilename())
        {
            binder << getValueOfFilename();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMimeType())
        {
            binder << getValueOfMimeType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getTotalSize())
        {
            binder << getValueOfTotalSize();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getChunkSize())
        {
            binder << getValueOfChunkSize();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getTotalChunks())
        {
            binder << getValueOfTotalChunks();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getUploadedChunksCount())
        {
            binder << getValueOfUploadedChunksCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getFileHash())
        {
            binder << getValueOfFileHash();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getCompressedSize())
        {
            binder << getValueOfCompressedSize();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[15])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[16])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> UploadSessions::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    if(dirtyFlag_[14])
    {
        ret.push_back(getColumnName(14));
    }
    if(dirtyFlag_[15])
    {
        ret.push_back(getColumnName(15));
    }
    if(dirtyFlag_[16])
    {
        ret.push_back(getColumnName(16));
    }
    return ret;
}

void UploadSessions::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAutomatedServiceId())
        {
            binder << getValueOfAutomatedServiceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDomain())
        {
            binder << getValueOfDomain();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTargetPath())
        {
            binder << getValueOfTargetPath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getFilename())
        {
            binder << getValueOfFilename();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMimeType())
        {
            binder << getValueOfMimeType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getTotalSize())
        {
            binder << getValueOfTotalSize();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getChunkSize())
        {
            binder << getValueOfChunkSize();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getTotalChunks())
        {
            binder << getValueOfTotalChunks();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getUploadedChunksCount())
        {
            binder << getValueOfUploadedChunksCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getFileHash())
        {
            binder << getValueOfFileHash();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getCompressedSize())
        {
            binder << getValueOfCompressedSize();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[15])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[16])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value UploadSessions::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getAutomatedServiceId())
    {
        ret["automated_service_id"]=getValueOfAutomatedServiceId();
    }
    else
    {
        ret["automated_service_id"]=Json::Value();
    }
    if(getDomain())
    {
        ret["domain"]=getValueOfDomain();
    }
    else
    {
        ret["domain"]=Json::Value();
    }
    if(getTargetPath())
    {
        ret["target_path"]=getValueOfTargetPath();
    }
    else
    {
        ret["target_path"]=Json::Value();
    }
    if(getFilename())
    {
        ret["filename"]=getValueOfFilename();
    }
    else
    {
        ret["filename"]=Json::Value();
    }
    if(getMimeType())
    {
        ret["mime_type"]=getValueOfMimeType();
    }
    else
    {
        ret["mime_type"]=Json::Value();
    }
    if(getTotalSize())
    {
        ret["total_size"]=(Json::Int64)getValueOfTotalSize();
    }
    else
    {
        ret["total_size"]=Json::Value();
    }
    if(getChunkSize())
    {
        ret["chunk_size"]=(Json::Int64)getValueOfChunkSize();
    }
    else
    {
        ret["chunk_size"]=Json::Value();
    }
    if(getTotalChunks())
    {
        ret["total_chunks"]=getValueOfTotalChunks();
    }
    else
    {
        ret["total_chunks"]=Json::Value();
    }
    if(getUploadedChunksCount())
    {
        ret["uploaded_chunks_count"]=getValueOfUploadedChunksCount();
    }
    else
    {
        ret["uploaded_chunks_count"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getFileHash())
    {
        ret["file_hash"]=getValueOfFileHash();
    }
    else
    {
        ret["file_hash"]=Json::Value();
    }
    if(getCompressedSize())
    {
        ret["compressed_size"]=(Json::Int64)getValueOfCompressedSize();
    }
    else
    {
        ret["compressed_size"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=getExpiresAt()->toDbStringLocal();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    return ret;
}

std::string UploadSessions::toString() const
{
    return toJson().toStyledString();
}

Json::Value UploadSessions::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 17)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getAutomatedServiceId())
            {
                ret[pMasqueradingVector[2]]=getValueOfAutomatedServiceId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDomain())
            {
                ret[pMasqueradingVector[3]]=getValueOfDomain();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getTargetPath())
            {
                ret[pMasqueradingVector[4]]=getValueOfTargetPath();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getFilename())
            {
                ret[pMasqueradingVector[5]]=getValueOfFilename();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getMimeType())
            {
                ret[pMasqueradingVector[6]]=getValueOfMimeType();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getTotalSize())
            {
                ret[pMasqueradingVector[7]]=(Json::Int64)getValueOfTotalSize();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getChunkSize())
            {
                ret[pMasqueradingVector[8]]=(Json::Int64)getValueOfChunkSize();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getTotalChunks())
            {
                ret[pMasqueradingVector[9]]=getValueOfTotalChunks();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getUploadedChunksCount())
            {
                ret[pMasqueradingVector[10]]=getValueOfUploadedChunksCount();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[11]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getFileHash())
            {
                ret[pMasqueradingVector[12]]=getValueOfFileHash();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getCompressedSize())
            {
                ret[pMasqueradingVector[13]]=(Json::Int64)getValueOfCompressedSize();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[14].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[14]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[14]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[15].empty())
        {
            if(getUpdatedAt())
            {
                ret[pMasqueradingVector[15]]=getUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[15]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[16].empty())
        {
            if(getExpiresAt())
            {
                ret[pMasqueradingVector[16]]=getExpiresAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[16]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getAutomatedServiceId())
    {
        ret["automated_service_id"]=getValueOfAutomatedServiceId();
    }
    else
    {
        ret["automated_service_id"]=Json::Value();
    }
    if(getDomain())
    {
        ret["domain"]=getValueOfDomain();
    }
    else
    {
        ret["domain"]=Json::Value();
    }
    if(getTargetPath())
    {
        ret["target_path"]=getValueOfTargetPath();
    }
    else
    {
        ret["target_path"]=Json::Value();
    }
    if(getFilename())
    {
        ret["filename"]=getValueOfFilename();
    }
    else
    {
        ret["filename"]=Json::Value();
    }
    if(getMimeType())
    {
        ret["mime_type"]=getValueOfMimeType();
    }
    else
    {
        ret["mime_type"]=Json::Value();
    }
    if(getTotalSize())
    {
        ret["total_size"]=(Json::Int64)getValueOfTotalSize();
    }
    else
    {
        ret["total_size"]=Json::Value();
    }
    if(getChunkSize())
    {
        ret["chunk_size"]=(Json::Int64)getValueOfChunkSize();
    }
    else
    {
        ret["chunk_size"]=Json::Value();
    }
    if(getTotalChunks())
    {
        ret["total_chunks"]=getValueOfTotalChunks();
    }
    else
    {
        ret["total_chunks"]=Json::Value();
    }
    if(getUploadedChunksCount())
    {
        ret["uploaded_chunks_count"]=getValueOfUploadedChunksCount();
    }
    else
    {
        ret["uploaded_chunks_count"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getFileHash())
    {
        ret["file_hash"]=getValueOfFileHash();
    }
    else
    {
        ret["file_hash"]=Json::Value();
    }
    if(getCompressedSize())
    {
        ret["compressed_size"]=(Json::Int64)getValueOfCompressedSize();
    }
    else
    {
        ret["compressed_size"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=getExpiresAt()->toDbStringLocal();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    return ret;
}

bool UploadSessions::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    else
    {
        err="The id column cannot be null";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if(pJson.isMember("automated_service_id"))
    {
        if(!validJsonOfField(2, "automated_service_id", pJson["automated_service_id"], err, true))
            return false;
    }
    if(pJson.isMember("domain"))
    {
        if(!validJsonOfField(3, "domain", pJson["domain"], err, true))
            return false;
    }
    if(pJson.isMember("target_path"))
    {
        if(!validJsonOfField(4, "target_path", pJson["target_path"], err, true))
            return false;
    }
    else
    {
        err="The target_path column cannot be null";
        return false;
    }
    if(pJson.isMember("filename"))
    {
        if(!validJsonOfField(5, "filename", pJson["filename"], err, true))
            return false;
    }
    else
    {
        err="The filename column cannot be null";
        return false;
    }
    if(pJson.isMember("mime_type"))
    {
        if(!validJsonOfField(6, "mime_type", pJson["mime_type"], err, true))
            return false;
    }
    if(pJson.isMember("total_size"))
    {
        if(!validJsonOfField(7, "total_size", pJson["total_size"], err, true))
            return false;
    }
    else
    {
        err="The total_size column cannot be null";
        return false;
    }
    if(pJson.isMember("chunk_size"))
    {
        if(!validJsonOfField(8, "chunk_size", pJson["chunk_size"], err, true))
            return false;
    }
    else
    {
        err="The chunk_size column cannot be null";
        return false;
    }
    if(pJson.isMember("total_chunks"))
    {
        if(!validJsonOfField(9, "total_chunks", pJson["total_chunks"], err, true))
            return false;
    }
    else
    {
        err="The total_chunks column cannot be null";
        return false;
    }
    if(pJson.isMember("uploaded_chunks_count"))
    {
        if(!validJsonOfField(10, "uploaded_chunks_count", pJson["uploaded_chunks_count"], err, true))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(11, "status", pJson["status"], err, true))
            return false;
    }
    if(pJson.isMember("file_hash"))
    {
        if(!validJsonOfField(12, "file_hash", pJson["file_hash"], err, true))
            return false;
    }
    if(pJson.isMember("compressed_size"))
    {
        if(!validJsonOfField(13, "compressed_size", pJson["compressed_size"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(14, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(15, "updated_at", pJson["updated_at"], err, true))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(16, "expires_at", pJson["expires_at"], err, true))
            return false;
    }
    return true;
}
bool UploadSessions::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 17)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[9] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[14].empty())
      {
          if(pJson.isMember(pMasqueradingVector[14]))
          {
              if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[15].empty())
      {
          if(pJson.isMember(pMasqueradingVector[15]))
          {
              if(!validJsonOfField(15, pMasqueradingVector[15], pJson[pMasqueradingVector[15]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[16].empty())
      {
          if(pJson.isMember(pMasqueradingVector[16]))
          {
              if(!validJsonOfField(16, pMasqueradingVector[16], pJson[pMasqueradingVector[16]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UploadSessions::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("automated_service_id"))
    {
        if(!validJsonOfField(2, "automated_service_id", pJson["automated_service_id"], err, false))
            return false;
    }
    if(pJson.isMember("domain"))
    {
        if(!validJsonOfField(3, "domain", pJson["domain"], err, false))
            return false;
    }
    if(pJson.isMember("target_path"))
    {
        if(!validJsonOfField(4, "target_path", pJson["target_path"], err, false))
            return false;
    }
    if(pJson.isMember("filename"))
    {
        if(!validJsonOfField(5, "filename", pJson["filename"], err, false))
            return false;
    }
    if(pJson.isMember("mime_type"))
    {
        if(!validJsonOfField(6, "mime_type", pJson["mime_type"], err, false))
            return false;
    }
    if(pJson.isMember("total_size"))
    {
        if(!validJsonOfField(7, "total_size", pJson["total_size"], err, false))
            return false;
    }
    if(pJson.isMember("chunk_size"))
    {
        if(!validJsonOfField(8, "chunk_size", pJson["chunk_size"], err, false))
            return false;
    }
    if(pJson.isMember("total_chunks"))
    {
        if(!validJsonOfField(9, "total_chunks", pJson["total_chunks"], err, false))
            return false;
    }
    if(pJson.isMember("uploaded_chunks_count"))
    {
        if(!validJsonOfField(10, "uploaded_chunks_count", pJson["uploaded_chunks_count"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(11, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("file_hash"))
    {
        if(!validJsonOfField(12, "file_hash", pJson["file_hash"], err, false))
            return false;
    }
    if(pJson.isMember("compressed_size"))
    {
        if(!validJsonOfField(13, "compressed_size", pJson["compressed_size"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(14, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(15, "updated_at", pJson["updated_at"], err, false))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(16, "expires_at", pJson["expires_at"], err, false))
            return false;
    }
    return true;
}
bool UploadSessions::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 17)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
      if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
      {
          if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, false))
              return false;
      }
      if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
      {
          if(!validJsonOfField(15, pMasqueradingVector[15], pJson[pMasqueradingVector[15]], err, false))
              return false;
      }
      if(!pMasqueradingVector[16].empty() && pJson.isMember(pMasqueradingVector[16]))
      {
          if(!validJsonOfField(16, pMasqueradingVector[16], pJson[pMasqueradingVector[16]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UploadSessions::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 14:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 15:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 16:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
