#!/usr/bin/env python3
"""
embed_web.py - Embed web assets into a C++ header using Zstandard compression.

Usage:

    # Generate web.hpp from a few assets
    python embed_web.py dashboard.html app.js style.css

    # Specify output file
    python embed_web.py dashboard.html app.js style.css -o web.hpp

    # Higher compression level
    python embed_web.py dashboard.html app.js style.css --level 22

Requirements:

    pip install zstandard

Example generated symbols:

    dashboard.html -> DASHBOARD_HTML
    app.js         -> APP_JS
    style.css      -> STYLE_CSS
"""

import argparse
import mimetypes
import re
from pathlib import Path

import zstandard as zstd


def make_identifier(path: Path) -> str:
    """
    dashboard.html -> DASHBOARD_HTML
    app.min.js     -> APP_MIN_JS
    """
    name = re.sub(r"[^A-Za-z0-9]", "_", path.name)
    name = re.sub(r"_+", "_", name)
    return name.upper()


def mime_type(path: Path) -> str:
    mime, _ = mimetypes.guess_type(path.name)
    return mime or "application/octet-stream"


def bytes_to_cpp_array(data: bytes) -> str:
    lines = []

    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append(
            "    " + ", ".join(f"0x{b:02X}" for b in chunk)
        )

    return ",\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Embed web assets into a C++ header using Zstd compression."
    )

    parser.add_argument(
        "files",
        nargs="+",
        help="Files to embed"
    )

    parser.add_argument(
        "-o",
        "--output",
        default="web.hpp",
        help="Output header file"
    )

    parser.add_argument(
        "--level",
        type=int,
        default=19,
        help="Zstd compression level (default: 19)"
    )

    args = parser.parse_args()

    compressor = zstd.ZstdCompressor(level=args.level)

    assets = []

    for filename in args.files:
        path = Path(filename)

        if not path.is_file():
            print(f"Skipping non-file: {path}")
            continue

        original = path.read_bytes()
        compressed = compressor.compress(original)

        assets.append({
            "symbol": make_identifier(path),
            "path": "/" + path.name,
            "mime": mime_type(path),
            "original_size": len(original),
            "compressed_size": len(compressed),
            "data": compressed,
        })

        ratio = 100.0 * (1.0 - len(compressed) / len(original))

        print(
            f"{path.name}: "
            f"{len(original)} -> {len(compressed)} bytes "
            f"({ratio:.1f}% saved)"
        )

    with open(args.output, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by embed_web.py\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstddef>\n")
        f.write("#include <cstdint>\n\n")

        f.write(
            "struct WebAsset\n"
            "{\n"
            "    const char* path;\n"
            "    const char* mime;\n"
            "    const uint8_t* data;\n"
            "    size_t compressed_size;\n"
            "    size_t original_size;\n"
            "};\n\n"
        )

        for asset in assets:
            f.write(
                f"constexpr uint8_t {asset['symbol']}[] = {{\n"
            )

            f.write(bytes_to_cpp_array(asset["data"]))

            f.write("\n};\n\n")

        f.write("constexpr WebAsset WEB_ASSETS[] = {\n")

        for asset in assets:
            f.write(
                "    {\n"
                f'        "{asset["path"]}",\n'
                f'        "{asset["mime"]}",\n'
                f"        {asset['symbol']},\n"
                f"        sizeof({asset['symbol']}),\n"
                f"        {asset['original_size']}\n"
                "    },\n"
            )

        f.write("};\n\n")

        f.write(
            "constexpr size_t WEB_ASSET_COUNT = "
            "sizeof(WEB_ASSETS) / sizeof(WEB_ASSETS[0]);\n"
        )

    print(f"\nGenerated: {args.output}")


if __name__ == "__main__":
    main()
